name: book_store_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^2.3.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter: 
    sdk: flutter
  dio: ^5.2.1+1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_pdfview: ^1.3.1
  path_provider: ^2.0.15
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.0
  flutter_stripe: ^9.2.2
  flutter_dotenv: ^5.1.0
  http: ^0.13.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/.env
  uses-material-design: true

